import React from 'react'
import Navbar from '../components/Navbar'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Calendar.module.scss'
import { Grid } from '@mui/material'

function calendar() {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>

      <Grid container alignItems="center" justifyContent="center" direction="row" className={styles.calendarContainer}>
        <Image src="/images/enrollBubblesTop.svg" layout="raw" width={100} height={100} className={styles.enrollBubblesTop}></Image>
        <Image src="/images/enrollBubblesBottom.svg" layout="raw" width={100} height={100} className={styles.enrollBubblesBottom}></Image>
        <Grid item className={styles.title} xs={12}>
          <h3 className={styles.calendarTitle}>Calendar</h3>
        </Grid>
        <Grid item className={styles.calendar} xs={12}>
          <iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=America%2FToronto&showTitle=0&showPrint=0&src=OWZyNTBuZGppNjlyOTJqZWNtOHQ4ZTZ1b2dAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&color=%2330E3CA" style={{border:'solid 1px #777', width:'100%', height:'100%', minWidth:'600px'}}  frameBorder="0" scrolling="yes"></iframe>
        </Grid>
      </Grid>
    </>
  )
}

export default calendar