import React, { useState } from 'react'
import { collection, getDocs, Timestamp } from "firebase/firestore"
import { Grid, Stack, Box } from '@mui/material'
import { db } from "../firebase-config"
import styles from '../styles/Events.module.scss'
import Navbar from '../components/Navbar'
import Head from 'next/head'

export async function getServerSideProps(context) {
  const querySnapshot = await getDocs(collection(db, "events"));

  let events = [];

  querySnapshot.forEach((doc) => {
    let event = {};
    event['id'] = doc.id;
    event['data'] = JSON.parse(JSON.stringify(doc.data()));   
    events.push(event);
  })
 
  return {
    props: {events}, // will be passed to the page component as props
  }
}

function getMonth(month) {
  let months = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];
  return months[month];
}

function EventItem({event}) {
  const startTimestamp = new Timestamp(parseInt(event.data.startTime.seconds),parseInt(event.data.startTime.nanoseconds));
  const endTimestamp = new Timestamp(parseInt(event.data.endTime.seconds),parseInt(event.data.endTime.nanoseconds));
  
  return (
    <Box className={styles.eventContainer}>
      <Grid container direction="row">
        <Grid item xs="auto" className={styles.eventDateBox}>
          <p className={styles.eventDateMonth}>{getMonth(startTimestamp.toDate().getMonth())}</p>
          <p className={styles.eventDateDate}>{startTimestamp.toDate().getDate()}</p>
        </Grid> 
        <Grid item xs>
          <p>{event.data.eventName}</p>
          <p>{event.data.details}</p>
        </Grid>
      </Grid>
    </Box>
  );
}

function events({events}) {
  const eventItems = events.map((event) =>
    <EventItem event={event} />
  );

  return (
    <div>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>

      <Grid container className={styles.topSection} direction="column" justifyContent="center"> 
        <Grid item className={styles.titlesContainer}>
            <h1 className={styles.title}>Upcoming Events</h1>
            <p className={styles.subtitle}>Aside from regular lessons, our organization also hosts informational seminars for extra-motivated students, as well as free trial lessons if you are unsure about committing to a course. Check out our upcoming events below!</p>
        </Grid>
      </Grid>

      <Grid container className={styles.botSection} direction="column">
        <Grid item>
          <Stack spacing={2}>
            {eventItems}
          </Stack>
        </Grid>
      </Grid>
    </div>
  )
}

export default events