import React, { useState, useEffect, useRef } from 'react'
import { collection, getDocs, Timestamp, orderBy, query } from "firebase/firestore"
import { Grid, Stack, Box } from '@mui/material'
import { db } from "../firebase-config"
import styles from '../styles/Events.module.scss'
import Navbar from '../components/Navbar'
import Head from 'next/head'
import Image from 'next/image'
import { IoFileTray } from 'react-icons/io5'
import { useLanguageContext } from '../context/LangContext';

export async function getServerSideProps(context) {
  const querySnapshot = await getDocs(query(collection(db, "events"), orderBy("startTime")));

  let events = [];

  querySnapshot.forEach((doc) => {
    let event = {};
    event['id'] = doc.id;
    event['data'] = JSON.parse(JSON.stringify(doc.data()));   
    events.push(event);
  })
 
  return {
    props: {events}, // will be passed to the page component as props
  }
}

function formatTime(timeStamp) {
  const hours = timeStamp.toDate().getHours();
  const mins = timeStamp.toDate().getMinutes();

  let time = "";

  if(hours == 0) {
    time += '12';
  } else if(hours > 12){
    time += hours - 12;
  } else {
    time += hours;
  }

  time += ':';

  if(mins == 0) {
    time += "00";
  } else if(mins < 10){
    time += "0";
    time += mins;
  } else {
    time += mins;
  }
 
  if(hours >= 12){
    time += " PM";
  } else {
    time += " AM";
  }

  return time;
}

function getMonth(month) {
  let months = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];
  return months[month];
}

function EventItem({event}) {
  const [isVisible, setVisible] = useState(false);
  const domRef = useRef();
  
  useEffect(() => {
    const observer = new IntersectionObserver(entries => {
      entries.forEach(entry => setVisible(entry.isIntersecting));
    });
    
    observer.observe(domRef.current);
  }, []);

  const startTimestamp = new Timestamp(parseInt(event.data.startTime.seconds),parseInt(event.data.startTime.nanoseconds));
  const endTimestamp = new Timestamp(parseInt(event.data.endTime.seconds),parseInt(event.data.endTime.nanoseconds));
  
  return (
    <Box ref={domRef}>
      <Grid container direction="row" className={`${styles.eventContainer} ${styles.fadeInSection} ${isVisible ? styles.isVisible : styles.fadeInSection}`}>
        <Grid container item xs="auto" className={styles.eventDateBox} justifyContent="center" direction="column">
          <p className={styles.eventDateMonth}>{getMonth(startTimestamp.toDate().getMonth())}</p>
          <p className={styles.eventDateDate}>{startTimestamp.toDate().getDate()}</p>
        </Grid> 
        <Grid container item xs className={styles.eventContentBox} spacing={1}>
          <Grid container item xs="auto" alignItems="flex-end" sx={{maxWidth:'100%'}}>
            <p className={styles.eventName}>{event.data.eventName}</p>
          </Grid>
          <Grid container item xs="auto" alignItems="flex-end">
            <div className={styles.eventTimeBox}>
              <p className={styles.eventTime}>{`${formatTime(startTimestamp)} - ${formatTime(endTimestamp)} EST`}</p>
            </div>
          </Grid>
          <Grid container item xs={12} alignItems="flex-start">
            <p className={styles.eventDetails}>{event.data.details}</p>
          </Grid>
        </Grid>
      </Grid>
    </Box>
  );
}

function events({events}) {
  const isEng = useLanguageContext().language;

  let eventsText = isEng ? 'Events' : '事件';

  const eventItems = events.map((event) => 
    <EventItem event={event} />
  );

  return (
    <>
      <Head>
        <title>{eventsText}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>

      <Grid container className={styles.topSection} direction="column" justifyContent="center"> 
        <Image src="/images/eventsTopLeftBubbles.svg" layout="raw" width={100} height={100} className={styles.bubblesTopLeft}></Image>
        <Image src="/images/eventsTopRightBubbles.svg" layout="raw" width={100} height={100} className={styles.bubblesTopRight}></Image>

        <Grid item className={styles.titlesContainer}>
            <h1 className={styles.title}>Upcoming Events</h1>
            <p className={styles.subtitle}>Aside from regular lessons, our organization also hosts informational seminars for extra-motivated students, as well as free trial lessons if you are unsure about committing to a course. Check out our upcoming events below!</p>
        </Grid>
      </Grid>

      <Grid container className={styles.botSection} direction="column">
        <Image src='/images/coursesBubblesLeft.svg' layout="raw" width={450} height={450} className={styles.bubblesLeft}></Image>
        <Image src='/images/coursesBubblesRight.svg' layout="raw" width={450} height={450} className={styles.bubblesRight}></Image>
        <Grid item sx={{overflowY: 'auto', paddingBottom: '30px', zIndex: 2}}>
          <Stack spacing={2}>
            {eventItems}
          </Stack>
        </Grid>
      </Grid>
    </>
  )
}

export default events