import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { Container, Grid, Button } from '@mui/material';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
        <Container className={styles.big}>
          <Grid container className={styles.startingContainer} alignItems="center" direction="row-reverse">
            <Image src="/images/startingBubbles.png" layout="raw" width={100} height={100} className={styles.startingBubbles}></Image>
            <Grid item container xs={12} sm={5} className={styles.startingRight} justifyContent="center">
              <Image src="/images/boy.svg" layout="raw" width={100} height={100} className={styles.boyImage}></Image>
            </Grid>
            <Grid item container xs={12} sm={7} className={styles.startingLeft}>
              <h1 className={styles.title}> Students to Students Tutoring </h1>
              <p className={styles.subtitle}>This summer, we’ll have classes suitable for all students, as well as free trial lessons and webinars open to the public!</p>
              <Button variant="contained" className={styles.searchButton}>Search Courses</Button>
            </Grid>
          </Grid>
        </Container>


      
    </div>
  )
}
